### ISSUE TITLE
Add link to team page in header

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/cityofzion-website#34]
The beautiful new team page should have a link in the header.  Currently you need to know the path to access it.

**Comment by Woodehh** [comment]
Hey there!

I agree. However, does the council approve this page in it's current stage? Since it's an addition, which seems sort-of accepted already, i reckon it has to run through the council.

@lllwvlvwlll Do you and the rest of the council approve? If so; i can have it ready in a couple of minutes :-)
